alias gs='git status'
alias gd='git diff'
alias gdc='git diff --cached'
alias gdm='git diff origin/master...@'
alias gdmno='git diff --name-only origin/master...@'
alias gdni='git diff --no-index --'
alias gdu='git diff @{u}'
alias gcm='git checkout master'
alias gdmnopy='git diff --name-only --diff-filter=ACM origin/master...@ | grep ".py$"'
alias gfom='git fetch origin master:master'
alias ll='ls -Alf --color=auto --show-control-chars'
alias gau='git add -u'
alias gaa='git add -A'
alias gf='git fetch'
alias gp='git push'
alias gpu='git push -u origin HEAD'
alias gpl='git pull'
alias gplr='git pull --rebase'
alias gb='git rev-parse --abbrev-ref HEAD'
alias gbc='gb | tee clip'
alias cd..='cd ..'
alias cc='git rev-parse HEAD'
alias cc='git rev-parse --short HEAD'
alias on='conda activate'
alias off='conda deactivate'

export EDITOR=vim
export HISTCONTROL=ignorespace
  
